// Generates the CSS custom properties consumed by apps/web/app/globals.css.
// Run via `pnpm --filter @vela/design-tokens build:css` (see package.json).
import { writeFileSync } from "node:fs";
import { colors, semantic, spacing, radius, elevation, motion, typography } from "./index";

function cssVarName(dotted: string): string {
  return `--${dotted.replace(/\./g, "-")}`;
}

function buildRootBlock(mode: "light" | "dark"): string {
  const lines: string[] = [];
  for (const [name, entry] of Object.entries(semantic)) {
    const ref = entry[mode];
    const value = ref.startsWith("#")
      ? ref
      : ref.startsWith("neutral.")
        ? colors.neutral[ref.split(".")[1] as keyof typeof colors.neutral]
        : `var(${cssVarName(ref.replace("color.", "color-"))})`;
    lines.push(`  ${cssVarName(name)}: ${value};`);
  }
  return lines.join("\n");
}

function buildStaticBlock(): string {
  const lines: string[] = [];
  for (const [name, entry] of Object.entries(colors)) {
    if (name === "neutral") continue;
    lines.push(`  ${cssVarName(`color-${name}`)}: ${(entry as { value: string }).value};`);
  }
  for (const [step, hex] of Object.entries(colors.neutral)) {
    lines.push(`  ${cssVarName(`neutral-${step}`)}: ${hex};`);
  }
  for (const [name, value] of Object.entries(spacing)) {
    lines.push(`  ${cssVarName(`space-${name}`)}: ${value};`);
  }
  for (const [name, value] of Object.entries(radius)) {
    lines.push(`  ${cssVarName(`radius-${name}`)}: ${value};`);
  }
  for (const [name, value] of Object.entries(elevation)) {
    lines.push(`  ${cssVarName(`elevation-${name}`)}: ${value};`);
  }
  for (const [name, entry] of Object.entries(motion)) {
    if (typeof entry === "number") continue;
    lines.push(`  ${cssVarName(`motion-${name}`)}: ${entry.duration} ${entry.easing};`);
  }
  for (const [name, entry] of Object.entries(typography)) {
    lines.push(`  ${cssVarName(`type-${name}-size`)}: ${entry.size};`);
    lines.push(`  ${cssVarName(`type-${name}-line-height`)}: ${entry.lineHeight};`);
    lines.push(`  ${cssVarName(`type-${name}-weight`)}: ${entry.weight};`);
  }
  return lines.join("\n");
}

const output = `/* AUTO-GENERATED by @vela/design-tokens/src/css.ts — do not hand-edit. */
:root {
${buildStaticBlock()}
${buildRootBlock("dark")}
}

:root[data-theme="light"] {
${buildRootBlock("light")}
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]) {
${buildRootBlock("light")}
  }
}
`;

writeFileSync(new URL("../dist/tokens.css", import.meta.url), output);
