import type { Config } from "tailwindcss";

// Every value below resolves to a CSS custom property generated by
// @vela/design-tokens (packages/design-tokens/src/css.ts) — never a literal
// hex/px value. Arbitrary Tailwind values (`bg-[#C9A84C]`) are a code-review
// rejection per Handbook 4.4; this file is the single place new tokens get
// wired in, not a place to work around it with a one-off arbitrary value.
const config: Config = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        midnight: "var(--color-midnight)",
        gold: "var(--color-gold)",
        "gold-dark": "var(--color-goldDark)",
        cobalt: "var(--color-cobalt)",
        slate: "var(--color-slate)",
        sage: "var(--color-sage)",
        rust: "var(--color-rust)",
        neutral: {
          0: "var(--color-neutral-0)",
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
          700: "var(--color-neutral-700)",
          800: "var(--color-neutral-800)",
          900: "var(--color-neutral-900)",
        },
        surface: {
          canvas: "var(--surface-canvas)",
          raised: "var(--surface-raised)",
          overlay: "var(--surface-overlay)",
          primary: "var(--surface-primary)",
          secondary: "var(--surface-secondary)",
        },
        border: {
          DEFAULT: "var(--border-default)",
          strong: "var(--border-strong)",
        },
        text: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          disabled: "var(--text-disabled)",
          onAccent: "var(--text-onAccent)",
        },
        action: {
          primary: "var(--action-primary)",
          primaryText: "var(--action-primaryText)",
        },
        status: {
          success: "var(--status-success)",
          warning: "var(--status-warning)",
          danger: "var(--status-danger)",
        },
        data: {
          aiAccent: "var(--data-aiAccent)",
        },
      },
      fontFamily: {
        display: ["var(--font-display)", "Georgia", "serif"],
        ui: ["var(--font-ui)", "-apple-system", "sans-serif"],
        data: ["var(--font-data)", "Courier New", "monospace"],
      },
      spacing: {
        0: "var(--space-0)",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        9: "var(--space-9)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        1: "var(--elevation-1)",
        2: "var(--elevation-2)",
        3: "var(--elevation-3)",
        modal: "var(--elevation-modal)",
      },
      transitionDuration: {
        instant: "100ms",
        quick: "180ms",
        standard: "240ms",
        deliberate: "400ms",
      },
    },
  },
  plugins: [],
};

export default config;
