import type { Metadata } from "next";
import { LegalPageLayout } from "@/components/legal/LegalPageLayout";

export const metadata: Metadata = {
  title: "Privacy Policy | VELA",
};

const UPDATED = "9 August 2026";
const CONTACT_EMAIL = "kennzyoguh@gmail.com";

export default function PrivacyPage() {
  return (
    <LegalPageLayout title="Privacy Policy" updated={UPDATED}>
      <p>
        This Privacy Policy explains what information VELA collects, how we use it, and the choices
        you have. It applies to everyone who uses VELA — business owners, their staff, and the
        accountants they invite.
      </p>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">1. What we collect</h2>
        <p>
          We collect information you give us directly, and information generated by using the
          service:
        </p>
        <ul className="ml-5 mt-2 flex list-disc flex-col gap-1.5">
          <li>
            Account details: name, email, phone number, business name and registration status.
          </li>
          <li>
            Business data: invoices, clients, products, sales, bank transactions you connect,
            payroll and employee records, and compliance obligations you track.
          </li>
          <li>
            Payment data: Paystack processes card and bank details directly — we never see or store
            your customers&apos; full card numbers.
          </li>
          <li>
            Device and usage data: login timestamps, IP address, and the device a staff PIN login is
            bound to (part of how we prevent stolen PINs from being used elsewhere).
          </li>
        </ul>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">2. How we use it</h2>
        <p>We use your information to:</p>
        <ul className="ml-5 mt-2 flex list-disc flex-col gap-1.5">
          <li>
            Operate the service — generate invoices, run payroll, calculate compliance figures,
            process payments.
          </li>
          <li>
            Send account, security, and transactional notifications (email, SMS, or WhatsApp) —
            verification links, payment confirmations, compliance reminders, daily summaries.
          </li>
          <li>Detect and prevent fraud, unauthorised access, and abuse.</li>
          <li>
            Improve the product, including deterministic and AI-generated insights (Ask Vela)
            computed from your own organisation&apos;s data only.
          </li>
        </ul>
        <p className="mt-2">We do not sell your data.</p>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">3. Who we share it with</h2>
        <p>
          We share data only with the processors that make the service work, each bound by their own
          terms:
        </p>
        <ul className="ml-5 mt-2 flex list-disc flex-col gap-1.5">
          <li>
            <strong>Paystack</strong> — payment processing.
          </li>
          <li>
            <strong>Termii</strong> — SMS and WhatsApp delivery.
          </li>
          <li>
            <strong>Resend</strong> — transactional email delivery.
          </li>
          <li>
            <strong>Anthropic</strong> — powers Ask Vela; only the specific figures needed to answer
            your question are sent, never your full database.
          </li>
          <li>
            Infrastructure providers hosting our application and database, under standard hosting
            agreements.
          </li>
        </ul>
        <p className="mt-2">
          We disclose information beyond this only if required by law or to protect the rights,
          property, or safety of VELA, our users, or the public.
        </p>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">4. How we protect it</h2>
        <p>
          Every organisation&apos;s data is isolated at the database level with row-level security,
          not just an application-side check. Access tokens are independently re-verified on every
          request. Sensitive actions — role changes, invites, discount approvals, staff device
          resets — are recorded in an audit trail. Passwords and PINs are hashed, never stored in
          plain text.
        </p>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">5. Your rights</h2>
        <p>
          You can access, correct, or export your business data at any time from within VELA. You
          can request deletion of your account and associated personal data by contacting us —
          we&apos;ll retain only what we&apos;re legally required to (for example, financial records
          subject to statutory retention periods). If you&apos;re in Nigeria, these rights are
          consistent with the Nigeria Data Protection Act.
        </p>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">6. Cookies</h2>
        <p>
          We use a small number of essential cookies to keep you signed in and to protect against
          cross-site request forgery. We don&apos;t use third-party advertising or tracking cookies.
        </p>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">7. Data retention</h2>
        <p>
          We keep your data for as long as your account is active, and afterward only as long as
          needed for legitimate business or legal purposes, such as tax and financial record
          requirements.
        </p>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">8. Changes to this policy</h2>
        <p>
          We may update this policy as VELA evolves. Material changes will be communicated by email
          or an in-app notice before they take effect.
        </p>
      </div>

      <div>
        <h2 className="font-ui text-[1.05rem] font-bold">9. Contact</h2>
        <p>
          Questions about this policy, or requests relating to your data, can be sent to{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-data-aiAccent hover:underline">
            {CONTACT_EMAIL}
          </a>
          .
        </p>
      </div>
    </LegalPageLayout>
  );
}
